name = "zodiac-service"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages 빌드 출력 디렉토리
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_ENV = "production"
